export default [
  {
    name: 'id',
    label: 'admin.generic.table.id',
    field: 'id',
    sortable: true,
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 75px',
    headerStyle: 'width: 75px',
  },
  {
    name: 'full_name',
    label: 'admin.communication.contact.table.full_name',
    field: 'full_name',
    format: (val: string) => `${val}`,
    sortable: true,
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 100px',
    headerStyle: 'width: 100px',
    sort: (a: string, b: string) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: 'email',
    label: 'admin.communication.contact.table.email',
    field: 'email',
    format: (val: string) => `${val}`,
    sortable: true,
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 100px',
    headerStyle: 'width: 100px',
    sort: (a: string, b: string) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: 'subject',
    label: 'admin.communication.contact.table.subject',
    field: 'subject',
    format: (val: string) => `${val}`,
    sortable: true,
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 100px',
    headerStyle: 'width: 100px',
    sort: (a: string, b: string) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: 'actions',
    label: 'admin.generic.table.actions',
    field: 'actions',
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 100px',
    headerStyle: 'width: 100px',
  },
];
