// TODO: after finishing pages api

export default [
  {
    name: 'id',
    label: 'admin.generic.table.id',
    field: 'id',
    sortable: true,
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 75px',
    headerStyle: 'width: 75px',
  },
  {
    name: 'name',
    label: 'admin.communication.newsletter.table.name',
    field: 'name',
    format: (val: string) => `${val}`,
    sortable: true,
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 100px',
    headerStyle: 'width: 100px',
    sort: (a: string, b: string) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: 'valid_from',
    label: 'admin.communication.newsletter.table.valid_from',
    field: 'valid_from',
    format: (val: string) => `${val}`,
    sortable: true,
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 100px',
    headerStyle: 'width: 100px',
    sort: (a: string, b: string) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: 'valid_to',
    label: 'admin.communication.newsletter.table.valid_to',
    field: 'valid_to',
    format: (val: string) => `${val}`,
    sortable: true,
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 100px',
    headerStyle: 'width: 100px',
    sort: (a: string, b: string) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: 'is_active',
    label: 'admin.communication.newsletter.table.is_active',
    field: 'is_active',
    format: (val: string) => `${val}`,
    sortable: true,
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 100px',
    headerStyle: 'width: 100px',
    sort: (a: string, b: string) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: 'actions',
    label: 'admin.generic.table.actions',
    field: 'actions',
    align: 'center' as 'left' | 'right' | 'center',
    style: 'width: 100px',
    headerStyle: 'width: 100px',
  },
];
